# Lec07 - 코틀린에서 예외 다루는 방법
## try-catch-finally 구문
Java와 Kotlin의 try-catch문은 문법적으로 동일하다.
```java
// Java
private int parseIntOrThrow(@NotNull String str) {
        try {
        return Integer.parseInt(str);
        }catch (NumberFormatException e) {
        throw new IllegalArgumentException(String.format("주어진 %s는 숫자가 아닙니다.", str));
        }
        }
```
```kotlin
fun parseIntOrThrow(str: String): Int {
    try {
        return str.toInt()
    } catch (e: NumberFormatException) {
        throw IllegalArgumentException("주어진 ${str}은 숫자가 아닙니다.")
    }
}
```
다만 해당 구문 catch문에서 예외를 던지는 것이라 아니라 어떠한 값을 return할 때 사용법이 조금 달라진다.
```java
// Java
private Integer parseIntOrThrowV2(@NotNull String str) {
        try {
            return Integer.parseInt(str);
        }catch (NumberFormatException e) {
            return null;
        }
    }
```
```kotlin
// Kotlin
fun parseIntOrThrowV2(str: String): Int? {
    return try {
        str.toInt()
    } catch (e: NumberFormatException) {
        null
    }
}
```
kotlin에서의 try-catch문은 if-else문처럼 하나의 Expression으로 간주되기 때문에 바로 return문을 사용할 수 있다.

## Checked Exception과 Unchecked Exception
```java
// Java
private void readFile() throws IOException {
        File currentFile = new File(".");
        File file = new File(currentFile.getAbsoluteFile() + "/a.txt");
        BufferedReader reader = new BufferedReader(new FileReader(file));
        System.out.println(reader.readLine());
        reader.close();
    }
```
```kotlin
// Kotlin
fun readFile(path: String) {
        val currentFile = File(".")
        val file = File(currentFile.absolutePath + "/a.txt")
        val reader = BufferedReader(FileReader(file))
        println(reader.readLine())
        reader.close()
    }
```
위 코드는 Java와 Kotlin으로 작성한 동일한 코드이다. 두 개의 코드에서 문법적인 부분을 제외하고 다른 점을 찾는다면 Java 코드에는 `throws` 구문이
있고 Kotlin에서는 없다는 점이다.

그 이유는 Kotlin에서는 Checked Exception(예외가 발생함을 명시하는 Excepttion)과 Unchecked Exception을 구분하지 않고 '
모두 Unchecked Exception으로 간주하기 때문이다.